- name: Install Docker, Git, Maven
  hosts: all
  become: yes
  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install Maven
      apt:
        name: maven
        state: present
        update_cache: yes
        
    - name: Set Docker socket permissions
      file:
        path: /var/run/docker.sock
        mode: '0777'
